import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const css = await readFile(join(root, "graphite-teal.css"), "utf8");
const output = [
  "<!-- Generated by build-theme.mjs; edit graphite-teal.css instead. -->",
  "<style>",
  css.trim(),
  "</style>",
  "",
].join("\n");

await writeFile(join(root, "theme-head.html"), output);
