# Include these options in the [global] section of your copyparty config.
# /canal1 only needs to be a private bind mount inside the container.

[global]
  themes: 12
  theme: 11
  tcolor: e9efed
  html-head: @/canal1/theme-head.html
